### ISSUE TITLE
statis resources are missing

### ISSUE THREAD

**Issue by tsabi** [Kozea/wdb#120]
Installed through pipy, and got this error on the server's console:
[W 180610 19:38:22 web:2106] 404 GET /static/hipster.jpg (10.1.0.100) 0.81ms

The file is in the git repo, but there is no rule to include in the tarball.
Another file what is missing is: /static/libs/material-design-lite/material.min.js.map. It don't do any problem, just i see in the browsers console it tries to download it and it doesn't exist.

**Comment by paradoxxxzero** [comment]
Thanks for pointing that out, I don't know how I missed that.
As for the source map, there's no need in production so it's a safe ignore.
