### ISSUE TITLE
question: how long does it take wdb to trigger? (on the Docker setup)

### ISSUE THREAD

**Issue by okeyokoro** [Kozea/wdb#128]
I'm running `wdb` using the `Docker` workflow prescribed in the README.

But, I have to say I'm a little unsatisfied with the speed (the time it takes for a session to start. given that I've triggered the route where the `import wdb; wdb.set_trace()` is placed)

I'd like to ask for any tips, suggestions,...perhaps there's something I'm missing?

**Comment by okeyokoro** [comment]
ran it on a smaller application/setup for context.

I can confirm that it can be pretty fast under the right conditions. Also ran into issues: #127 #99 along the way

**Comment by paradoxxxzero** [comment]
Thanks for the feedback, what particularities does your first application have? Is the stacktrace big by any chance?

**Comment by okeyokoro** [comment]
> what particularities does your first application have? Is the stacktrace big by any chance?

it's a pretty large legacy-ish python app... so I would think so.
