### ISSUE TITLE
Make wdb easier to run on Windows

### ISSUE THREAD

**Issue by egasimus** [Kozea/wdb#17]
I'm developing on a Windows machine, and I have associated `.py` files with my text editor of choice, as opposed to the Python interpreter. This makes it difficult for me to run the wdb server from the command line, even though the directory where `wdb.server.py` is on my system path: if I type out just `wdb.server.py`, I only open it in my IDE; and if I put `python` in front of that, the shell can't find that file so I need to copy the entire path to it.

Proposed solution: add a .exe version of wdb.server.py for Windows installations, as is customary with many tools such as pip, Nose or Fabric.

**Comment by Tset-Noitamotua** [comment]
I ran into the same issue right now. README.md could mention usage on Windows or tell that Windows is not supported at all - if it is so.

I tried this ...
```shell
C:\>python C:\Python27\Scripts\wdb.server.py
```
... but got an error
```shell
C:\>python C:\Python27\Scripts\wdb.server.py
[E 170124 13:17:18 ioloop:633] Exception in callback <functools.partial object a
t 0x038D2BD0>
    Traceback (most recent call last):
      File "C:\Python27\lib\site-packages\tornado\ioloop.py", line 604, in _run_
callback
        ret = callback()
      File "C:\Python27\lib\site-packages\tornado\stack_context.py", line 275, i
n null_wrapper
        return fn(*args, **kwargs)
      File "C:\Python27\lib\site-packages\wdb_server\__init__.py", line 306, in
callback
        info = json.loads(response.buffer.read().decode('utf-8'))
    AttributeError: 'NoneType' object has no attribute 'read'
```

@egasimus Did you managed to run it on Windows?

**Comment by Tset-Noitamotua** [comment]
EDIT

It works on Windows!

1. install wdb server and client as descriped in README.md
2. open a cmd and start the server `C:\>python C:\Python27\Scripts\wdb.server.py` NOTE: adjust to your path to `wdb.server.py` and ignore the errors in cmd.
3. open browser to http://localhost:1984/ --> your should now see something like that
![image](https://cloud.githubusercontent.com/assets/5635462/22249401/2471fe08-e243-11e6-98b0-52225fe3ae0f.png)

4a. open another cmd and run `wbd` or `wdb.exe` --> Client opens in your default browser
![image](https://cloud.githubusercontent.com/assets/5635462/22249446/46475e92-e243-11e6-951e-78d4be848a1d.png)

or 4b. open another cmd and run `python -m wdb your_file.py`  --> you get smt like that in your browser
![image](https://cloud.githubusercontent.com/assets/5635462/22249524/a03865cc-e243-11e6-817f-019cf61eda46.png)
