### ISSUE TITLE
Keyboard Shortcuts cheat sheet on Web UI

### ISSUE THREAD

**Issue by juancarlospaco** [Kozea/wdb#26]
Will be nice to have the Keyboard Shortcuts cheat sheet on the Web UI, 
as a Modal popup with a button to show it.

**Comment by s0undt3ch** [comment]
:+1:

**Comment by leorochael** [comment]
There is a `.h` command which displays all commands and their shortcuts.

I guess there should be a message somewhere in the web UI telling people to type `.h` to learn about the commands, but other than that, this help is good enough for me.

**Comment by paradoxxxzero** [comment]
There is now in last git version (with a nice (?) button!)
