### ISSUE TITLE
debugger (web-frontend) does not react to key-strokes

### ISSUE THREAD

**Issue by marcopashkov** [Kozea/wdb#29]
Hi,  

First of all - thank you for writing such a nice tool and sharing it!  
I am using `Chrome 33.0.1750.152` on `MacOSX 10.9.2` and cannot use the following keyboard commands in the web-frontend.
```
[Ctrl] + [↓] or [F11]    : Step into
[Ctrl] + [→] or [F10]    : Step over (Next)
[Ctrl] + [↑] or [F9]     : Step out (Return)
[Ctrl] + [←] or [F8]     : Continue
```
The equivalent shell-commands (e.g. `.s` etc) work, but not the function keys.
I hope I am not doing something potentially wrong, but even in this case the documentation might need an update.

Thanks,
Marco

**Comment by s0undt3ch** [comment]
Same here, Chromium 43.0.2357.130 (64-bit) on Linux

**Comment by paradoxxxzero** [comment]
Do you use last version ? Did you try without any chrome plugin ? Is there some errors in the console ?
