### ISSUE TITLE
Page http://localhost:1984/ flickers lots under Safari/Chrome on MacOS X.

### ISSUE THREAD

**Issue by GrahamDumpleton** [Kozea/wdb#35]
Something wrong with the CSS that causes flickering under Safari/Chrome on MacOS X. Under Firefox is fine.

Startup URL and then make a request to get even just one active session and issue occurs immediately and keeps happening.

Hard to capture without taking an actual video.

**Comment by subssn21** [comment]
This is not a CSS issue. If you look at the console log There are constant web socket open/close being sent with exceptions occuring


6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
7status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
5status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 Uncaught InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 Uncaught InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
5status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 Uncaught InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
5status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 Uncaught InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
5status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
5status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
4status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
5status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 Uncaught InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
5status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 Uncaught InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
5status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 Uncaught InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
5status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
7status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
7status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
6status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 Uncaught InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket open [Event]
status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket closed [CloseEvent]
4status.min.js?v=f4921c513cf6f1a0d6302f049c630a97:3 WebSocket is already in CLOSING or CLOSED state.
