### ISSUE TITLE
UI doesn't work on Safari

### ISSUE THREAD

**Issue by white-hat** [Kozea/wdb#39]
UI is completely broken on Safari Version 8.0.2 (10600.2.5)
![screenshot 2015-01-12 11 29 21](https://cloud.githubusercontent.com/assets/922988/5709395/515e87cc-9a4e-11e4-8489-62f66ef4ee8a.png)

**Comment by wong2** [comment]
@paradoxxxzero this could be closed right?

**Comment by paradoxxxzero** [comment]
Yes thanks
