### ISSUE TITLE
Code completion not working

### ISSUE THREAD

**Issue by OmeGak** [Kozea/wdb#40]
Just wondering if I'm missing some dependencies, it's a jedi problem, or the integration of wdb with jedi is working somewhat sloppy only for me. Does anybody else notice bad to completely nonexistent code completion?

**Comment by paradoxxxzero** [comment]
Strange. Are you up to date with jedi ? Have you tried the git version of wdb ?

**Comment by OmeGak** [comment]
I believe I'm up to date with jedi (`0.8.1-final0`). I'll try with the git version, but I've been noticing this since I started using wdb half a year ago. The way in which it acts sloppy is that for most variables I'm not suggested completion after typing `.`, or that the suggestion is completely generic and not related with the actual members.

**Comment by paradoxxxzero** [comment]
This https://github.com/Kozea/wdb/commit/3d98ca8d9430ac4df8a4d9e03fdd27340b7a7e53 should have fixed your problem or maybe it caused it...

**Comment by OmeGak** [comment]
Somewhat, the github version seems to be working flawlessly so far. Thanks a lot!

**Comment by paradoxxxzero** [comment]
Nice, it will soon be the time to make a new release.
