### ISSUE TITLE
Add official docker image

### ISSUE THREAD

**Issue by Yajo** [Kozea/wdb#44]
[The docker instructions tell us to use the image Kozea/wdb-server](https://github.com/Kozea/wdb/commit/6f51fbbb21fe5d14944fb14750beac08a2551209?diff=unified#diff-04c6e90faac2675aa89e2176d2eec7d8R329), but that image does not exist (and BTW, it should not have a capital K).

It would be nice to have a official image out there.

**Comment by Yajo** [comment]
Still no kozea/wdb-server image in the docker hub...

**Comment by paradoxxxzero** [comment]
Wait for it... :)

**Comment by paradoxxxzero** [comment]
Could you try to see if I did everything correctly ? (I am fairly new to docker)

**Comment by Yajo** [comment]
IMHO it would be much better if you had the image linked to this same repository. It implies adding just one Dockerfile and lets you install directly from source and have automatically 1 image tag per git tag. Tagging is very common in the Docker world because it lets you avoid surprises with new versions (same as with `pip freeze`).

Would you mind if I send a PR so that you can remove the https://github.com/Kozea/docker-wdb-server repository?

**Comment by Yajo** [comment]
I'd tell you too the settings for it.

**Comment by paradoxxxzero** [comment]
I would indeed appreciate a PR! Thanks
