### ISSUE TITLE
[Question] Under a tornado app, write an error while holding the debug session open

### ISSUE THREAD

**Issue by s0undt3ch** [Kozea/wdb#55]
This is more of a question than a bug, a possible feature request.

I don't know the full code base of wdb so I better ask first. Is it possible that, under a tornado application, when an exception occurs, to write something as a response to the request yet, still locking the debug session for further investigation?

**Comment by paradoxxxzero** [comment]
It would be possible to keep the globals / locals of every stack level of the exception and use them later in the eval prompt. Any stepping is impossible though.

**Comment by s0undt3ch** [comment]
Hmm, that defeats the main purpose of a debugger.... Thanks!
