### ISSUE TITLE
Post Mortem debugging

### ISSUE THREAD

**Issue by leorochael** [Kozea/wdb#64]
Hi,

While trying to understand errors in large swathes of code I usually turn

```python
function_that_call_large_swathes_of_code(some, params)
```
Into:

```python
try:
    function_that_call_large_swathes_of_code(some, params)
except:
    import pdb; pdb.post_mortem()
    raise
```

This gives me a pdb prompt right in the point where an error was raised, allowing me to evaluate expressions in that frame and all frames above it.

If I use `pdb.set_trace()` instead of `pdb.post_mortem()`, I get an almost useless pdb prompt at the point where the error was caught instead of where the error was raised.

I wish there was a `wdb.post_mortem()` that worked like a `pdb.post_mortem()`, but there isn't, and calling `wdb.set_trace()` inside the `except:` clause has the same limited utility as `pdb.set_trace()`.

By the way, I did try calling:
```python
wdb.set_trace(sys.exc_info()[2].tb_frame)
```

As well as:
```python
wdb.set_trace(sys.exc_info()[2].tb_next.tb_frame)
```

But all I got was the same as if I had called `wdb.set_trace()`. Probably because `wdb` is setting traces in all those traceback frames, but only the exception catching frame is alive and traceable, so it's the only one that gets traced.

Then it dawned on me that `pdb.post_mortem()` doesn't actually set any traces, it directly interacts with the exception traceback, so I managed to get the equivalent of `pdb.post_mortem()` with the following code:

```python
import wdb
exc_info = sys.exc_info()
wdb.Wdb.get().handle_exception(frame=exc_info[2].tb_frame, exc_info=exc_info)
```

Since the above is a mouthful, it would be nice to have a `wdb.post_mortem()` that did the above, as well as a shortcut for it like `w.tf` is for `wdb.set_trace()`.

Notice that `pdb.Pdb.setup()` (called indirectly by `pdb.post_mortem()`) does some dance with `traceback.tb_frame` and `traceback.tb_next`, to handle nested exceptions I think, and it might be necessary for wdb to do a similar dance.

**Comment by paradoxxxzero** [comment]
Did you try `wdb.post_mortem()` ?
https://github.com/Kozea/wdb/blob/master/client/wdb/__init__.py#L937

**Comment by leorochael** [comment]
:confused: I could swear it wasn't there the last time I looked...

I guess we just need to see if there is a difference between calling `handle_exception()` (like the snippet in my comment) or calling `interaction()` directly like `wdb.post_mortem()` does.
