### ISSUE TITLE
How can I get the same UI as the screenshot?

### ISSUE THREAD

**Issue by wong2** [Kozea/wdb#66]
Hi, I tried wdb for a while, but I can't get the same UI as the screenshot

**Comment by paradoxxxzero** [comment]
Use the git version, there's no release with the new UI yet

**Comment by wong2** [comment]
@paradoxxxzero when will there be a new release?

**Comment by paradoxxxzero** [comment]
When it's almost stable, you can help by testing the new version though :+1:

**Comment by wong2** [comment]
@paradoxxxzero yeah, I've tried the git version, it's amazing! can't wait to integrate it to my workflow

**Comment by paradoxxxzero** [comment]
Glad you like it :)
