### ISSUE TITLE
Show filename in session list?

### ISSUE THREAD

**Issue by wong2** [Kozea/wdb#75]
Currently if several developers use the same wdb server, it's hard to distinguish sessions from each other, maybe we could show debugging filename to help with this situation?

**Comment by paradoxxxzero** [comment]
I think this was named as a security issue.

**Comment by wong2** [comment]
@paradoxxxzero so wdb don't recommend the "several developers share a wdb server" model?

**Comment by paradoxxxzero** [comment]
If it works for you it's great, we could add an option for people aware of that risk

**Comment by wong2** [comment]
@paradoxxxzero yeah, what we're working on is public between me and my co-workers
