### ISSUE TITLE
how to run with pytest?

### ISSUE THREAD

**Issue by garfieldnate** [Kozea/wdb#79]
Is there any simple way to debug tests run with `pytest`? It takes a `--pdb` parameter to debug tests with the built-in debugger, but I'm not sure how to run with wdb instead.

**Comment by paradoxxxzero** [comment]
Install the pytest-wdb package and use - -wdb

Le ven. 15 juil. 2016 04:10, Nathan Glenn <notifications@github.com> a
écrit :

**Comment by blaggacao** [comment]
Looks like this does not work.
Alternative: `--pdb --pdbcls wdb:Wdb`
But on `CTRL + C` raises:
```
INTERNALERROR>   File "/usr/local/lib/python3.5/dist-packages/_pytest/debugging.py", line 311, in _enter_pdb
INTERNALERROR>     post_mortem(tb)
INTERNALERROR>   File "/usr/local/lib/python3.5/dist-packages/_pytest/debugging.py", line 328, in post_mortem
INTERNALERROR>     if p.quitting:
INTERNALERROR> AttributeError: 'Wdb' object has no attribute 'quitting'


```

**Comment by blaggacao** [comment]
@paradoxxxzero Can you reopen?
