### ISSUE TITLE
I want to make sublime text wdb plugin.

### ISSUE THREAD

**Issue by Ashon** [Kozea/wdb#82]
Hello, I'm impressed to your `wdb`. :+1: 

I use SublimeText as python IDE.
so to use wdb more easily, now I'm making SublimeText's wdb plugin.
my repo is here. (https://github.com/Ashon/sublime-wdb now it is very inferior.. :P)

Anyway, while I make wdb plugin,
I wanted to run wdb server in python code.
but I cannot find the proper way... (now my plugin runs wdb server using `subprocess.Popen`.)

Can I get more hints?
Thank you.

**Comment by wong2** [comment]
just look at: https://github.com/Kozea/wdb/blob/master/server/wdb.server.py

**Comment by Ashon** [comment]
Oh.. so simple. I don't know why I missed this...
Thank you wong2.

Close this issue.
