### ISSUE TITLE
Sluggish to get variables values

### ISSUE THREAD

**Issue by Yajo** [Kozea/wdb#94]
I'm experiencing very sluggish variable evaluation, as you can see in this [screencast](https://github.com/Kozea/wdb/files/760250/Screencast_08-02-17_09.58.57.zip).

However, stepping in and out works quick as always.

Any clues on why this is happening? I'm on wdb 3.1.2 (both client and server).

**Comment by paradoxxxzero** [comment]
Wow this is very long indeed, is it happening only at debugger start or the second evaluation is long as well.
This may be due to importmagic background  indexing.

**Comment by Yajo** [comment]
It happens at every evaluation. In fact, stepping through the code is as fast as always, as you see in the video. That's how it should be, since all this happens in localhost.

It seems to me like the autocompletion feature tries to send & finish a request for each character I type before actually executing what I wrote. Maybe just aborting autocompletion requests when I have written a different character or pressed Enter would speed up this...

**Comment by paradoxxxzero** [comment]
There is a timeout that prevents completion to slow down the prompt: https://github.com/Kozea/wdb/blob/master/client/wdb/ui.py#L609 so it might be something else. I have trouble reproducing (but I remember seeing something like that while debugging a big project). Do you still reproduce if you `pip uninstall jedi importmagic uncompyle6`?

**Comment by Yajo** [comment]
No, can't reproduce after that.

**Comment by paradoxxxzero** [comment]
So we know for sure that isn't a completion/indexing problem.
Do you always have the problem or with this project only?

**Comment by Yajo** [comment]
I have no other project to check at hand right now, but it seems like if I prepend this to the beginning of the project, the variable inspection is normal:

```
somevar={
    "oh": "yeah"
}
import wdb; wdb.set_trace()
```

**Comment by paradoxxxzero** [comment]
This is really weird.
As I side note I managed to reproduce your initial behavior with jedi in a threaded environment (when I uninstall jedi client side the problem is gone). This is because the timeout on completion is based on signals and they don't seem to work in threads.
