### ISSUE TITLE
How to avoid 'Program has existed' while debugging a Flask view

### ISSUE THREAD

**Issue by tatsuhirosatou** [Kozea/wdb#99]
First of all, thanks for making this amazing debugger. I love coding in Emacs, instead of IDEs, but one downside of Emacs is not having a nice debugger interface. Your tool is an amazing solution.

I am having trouble using it while debugging a Flask view. I assume that the view is timing out before I can finish debugging. 

I run Flask with Docker using the following:

`CMD gunicorn koipun.app:create_app\(\) --config='gunicorn.py' -b 0.0.0.0:$PORT -w 3`

How could I stop the program from exiting? I can only get about 20s worth of debugging before it suddenly exits. 

![screenshot from 2017-08-06 19-11-54](https://user-images.githubusercontent.com/232527/29007904-36f6af3e-7adb-11e7-9a98-6178c87a0e23.png)

**Comment by paradoxxxzero** [comment]
I don't think this comes from wdb. It seems that your server has a connection timeout somewhere which kills the connection.

**Comment by tatsuhirosatou** [comment]
@paradoxxxzero Thanks for taking a look. You are correct. I solved it with: `CMD gunicorn koipun.app:create_app\(\) --config='gunicorn.py' --timeout 10000 -b 0.0.0.0:$PORT -w 3`

It might be good to add a note on the documentation about the timeout parameter.

**Comment by okeyokoro** [comment]
ran into this also
